name        = "Ergopti"
name8       = "ergo_1dk"
locale      = "fr"
variant     = "1DK"
author      = "Adrien MOYAUX"
description = "Disposition ergonomique optimisée pour le français, l’anglais et le code"
url         = "https://ergopti.fr"
geometry    = "ERGO"
version     = "2.2.0"

base = '''
╭╌╌╌╌╌┰─────┬─────┬─────┬─────┬─────┰─────┬─────┬─────┬─────┬─────┰╌╌╌╌╌┬╌╌╌╌╌╮
┆ €   ┃ 1   │ 2   │ 3   │ 4   │ 5   ┃ 6   │ 7   │ 8   │ 9   │ 0 ° ┃ %   ┆ º   ┆
┆ $   ┃     │     │     │     │     ┃     │     │     │     │   º ┃ %   ┆ =   ┆
╰╌╌╌╌╌╂─────┼─────┼─────┼─────┼─────╂─────┼─────┼─────┼─────┼─────╂╌╌╌╌╌┼╌╌╌╌╌┤
·     ┃ Q   │ Y   │ O   │ M   │ K   ┃ F   │ G   │ H   │ C   │ W   ┃ {   ┆ }   ┆
·     ┃   á │   â │   ô │   û │   æ ┃     │     │     │     │     ┃ [   ┆ ]   ┆
·     ┠─────┼─────┼─────┼─────┼─────╂─────┼─────┼─────┼─────┼─────╂╌╌╌╌╌┼╌╌╌╌╌┤
·     ┃ A   │ I   │ E   │ U   │ :   ┃ V   │ S   │ N   │ T   │ R   ┃ "   ┆ |   ┆
·     ┃   à │   î │   œ │   ù │ .   ┃     │   j │   ñ │     │     ┃ '   ┆ \   ┆
╭╌╌╌╌╌╂─────┼─────┼─────┼─────┼─────╂─────┼─────┼─────┼─────┼─────╂╌╌╌╌╌┴╌╌╌╌╌╯
┆     ┃ X   │ É   │ È   │ ;   │ Z   ┃ B   │ D   │ L   │ P   │*¨   ┃           ·
┆     ┃   ê │   í │   ó │ ,   │     ┃     │     │     │   ç │***¨ ┃           ·
╰╌╌╌╌╌┸─────┴─────┴─────┴─────┴─────┸─────┴─────┴─────┴─────┴─────┚ · · · · · ·
'''

altgr = '''
╭╌╌╌╌╌┰─────┬─────┬─────┬─────┬─────┰─────┬─────┬─────┬─────┬─────┰╌╌╌╌╌┬╌╌╌╌╌╮
┆  *¤ ┃   ₁ │   ₂ │   ₃ │   ₄ │   ₅ ┃   ₆ │   ₇ │   ₈ │   ₉ │   ₀ ┃   ‱ ┆   ª ┆
┆   € ┃   ¹ │   ² │   ³ │   ⁴ │   ⁵ ┃   ⁶ │   ⁷ │   ⁸ │   ⁹ │   ⁰ ┃   ‰ ┆   ° ┆
╰╌╌╌╌╌╂─────┼─────┼─────┼─────┼─────╂─────┼─────┼─────┼─────┼─────╂╌╌╌╌╌┼╌╌╌╌╌┤
·     ┃   „ │  *¤ │   ‰ │   − │   “ ┃   ” │   ≈ │     │   § │     ┃     ┆     ┆
·     ┃   ` │   @ │   % │   & │   « ┃   » │   ~ │   # │   $ │   ^ ┃     ┆     ┆
·     ┠─────┼─────┼─────┼─────┼─────╂─────┼─────┼─────┼─────┼─────╂╌╌╌╌╌┼╌╌╌╌╌┤
·     ┃   ≤ │   ≥ │   € │   £ │   … ┃   ¦ │   — │   – │     │     ┃     ┆     ┆
·     ┃   < │   > │   { │   } │   : ┃   | │   ( │   ) │   [ │   ] ┃     ┆     ┆
╭╌╌╌╌╌╂─────┼─────┼─────┼─────┼─────╂─────┼─────┼─────┼─────┼─────╂╌╌╌╌╌┴╌╌╌╌╌╯
┆     ┃   × │     │     │   · │   ¡ ┃     │     │   ≠ │   ± │   ¿ ┃           ·
┆     ┃   * │   / │   \ │   ; │   ! ┃   ' │   " │   = │   + │   ? ┃           ·
╰╌╌╌╌╌┸─────┴─────┴─────┴─────┴─────┸─────┴─────┴─────┴─────┴─────┚ · · · · · ·
'''

[spacebar]
shift       = "-"
altgr       = "_"
altgr_shift = "\u00a0"  # NO-BREAK SPACE
1dk         = "’"
1dk_shift   = "\u202f"  # NARROW NO-BREAK SPACE
