name        = "Optimot"
name8       = "opti1dk"
locale      = "fr"
variant     = "1DK"
author      = "Adrien MOYAUX"
description = "Adaptation 1DK de la disposition Optimot"
url         = "https://optimot.fr"
geometry    = "ERGO"
version     = "0.0.1"

base = '''
╭╌╌╌╌╌┰─────┬─────┬─────┬─────┬─────┰─────┬─────┬─────┬─────┬─────┰╌╌╌╌╌┬╌╌╌╌╌╮
┆ +   ┃ 1   │ 2   │ 3   │ 4   │ 5   ┃ 6   │ 7   │ 8   │ 9   │ º   ┃ €   ┆ %   ┆
┆ =   ┃     │     │     │     │     ┃     │     │     │     │ 0 ° ┃ €   ┆ %   ┆
╰╌╌╌╌╌╂─────┼─────┼─────┼─────┼─────╂─────┼─────┼─────┼─────┼─────╂╌╌╌╌╌┼╌╌╌╌╌┤
·     ┃ K   │ J   │ O   │ W   │ B   ┃ F   │ D   │ L   │ ?   │ Q   ┃ {   ┆ }   ┆
·     ┃   á │   í │     │     │     ┃     │     │   û │ ’ ? │     ┃ [   ┆ ]   ┆
·     ┠─────┼─────┼─────┼─────┼─────╂─────┼─────┼─────┼─────┼─────╂╌╌╌╌╌┼╌╌╌╌╌┤
·     ┃ A   │ I   │ E   │ U   │ :   ┃ P   │ T   │ S   │ R   │ N   ┃ "   ┆ |   ┆
·     ┃   è │   é │   œ │     │ .   ┃     │   z │   ô │     │   ñ ┃ '   ┆ \   ┆
╭╌╌╌╌╌╂─────┼─────┼─────┼─────┼─────╂─────┼─────┼─────┼─────┼─────╂╌╌╌╌╌┴╌╌╌╌╌╯
┆ Ê   ┃ X   │ Y   │ À   │*¨   │ ;   ┃ G   │ C   │ M   │ H   │ V   ┃           ·
┆   ^ ┃   ù │   æ │   ê │***¨ │ ,   ┃     │   ç │   î │     │   â ┃           ·
╰╌╌╌╌╌┸─────┴─────┴─────┴─────┴─────┸─────┴─────┴─────┴─────┴─────┚ · · · · · ·
'''

altgr = '''
╭╌╌╌╌╌┰─────┬─────┬─────┬─────┬─────┰─────┬─────┬─────┬─────┬─────┰╌╌╌╌╌┬╌╌╌╌╌╮
┆     ┃   ¹ │   ² │   ³ │   ⁴ │   ⁵ ┃   ⁶ │   ⁷ │   ⁸ │   ⁹ │   ⁰ ┃     ┆     ┆
┆     ┃   ₁ │   ₂ │   ₃ │   ₄ │   ₅ ┃   ₆ │   ₇ │   ₈ │   ₉ │   ₀ ┃     ┆     ┆
╰╌╌╌╌╌╂─────┼─────┼─────┼─────┼─────╂─────┼─────┼─────┼─────┼─────╂╌╌╌╌╌┼╌╌╌╌╌┤
·     ┃   „ │   „ │     │     │   “ ┃   ” │   § │   ≠ │   ¿ │     ┃     ┆     ┆
·     ┃   ` │   @ │   % │   ! │   « ┃   » │   $ │   = │   ' │     ┃     ┆     ┆
·     ┠─────┼─────┼─────┼─────┼─────╂─────┼─────┼─────┼─────┼─────╂╌╌╌╌╌┼╌╌╌╌╌┤
·     ┃   ≤ │   ≥ │     │     │   … ┃   ± │   — │   – │     │     ┃     ┆     ┆
·     ┃   < │   > │   { │   } │   : ┃   + │   ( │   ) │   [ │   ] ┃     ┆     ┆
╭╌╌╌╌╌╂─────┼─────┼─────┼─────┼─────╂─────┼─────┼─────┼─────┼─────╂╌╌╌╌╌┴╌╌╌╌╌╯
┆     ┃   × │     │     │     │   · ┃   ≈ │   € │   − │   £ │   ¦ ┃           ·
┆     ┃   * │   / │   \ │   " │   ; ┃   ~ │   ^ │   & │   # │   | ┃           ·
╰╌╌╌╌╌┸─────┴─────┴─────┴─────┴─────┸─────┴─────┴─────┴─────┴─────┚ · · · · · ·
'''

[spacebar]
shift       = "-"
altgr       = "_"
altgr_shift = "\u00a0"  # NO-BREAK SPACE
1dk         = "\u00a0"  # NO-BREAK SPACE
1dk_shift   = "\u202f"  # NARROW NO-BREAK SPACE
